name: simple-socket-fn-logger
on:
  push:
    branches:
      - 'main'

env:
  VERSION: 1.0.2

jobs:
  build-jar-job:
    name: 'Build JAR'
    runs-on: ubuntu-latest

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3.0.0

      - name: 'Setup Java 11'
        uses: actions/setup-java@v2.0.0
        with:
          java-version: 11

      - name: 'Build JAR'
        run: |
          ./gradlew shadowJar


  build-non-windows-image:
    name: 'Build Non-Windows Image'
    needs: [build-jar-job]
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        include:
          - os: 'ubuntu-latest'
            label: 'linux'
          - os: 'macos-latest'
            label: 'mac'
    runs-on: ${{matrix.os}}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3.0.0

      - name: 'Setup Java 11'
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 11

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: '22.0.0.2'
          java: java11

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: 'Get JAR Artifact'
        uses: actions/download-artifact@v3.0.0
        with:
          name: 'simple-socket-fn-logger-${{env.VERSION}}-all.jar'

      - name: 'Build Native Image'
        run: |
          native-image --no-server --no-fallback -H:ReflectionConfigurationResources=reflection-config.json -H:IncludeResources=logback.xml --allow-incomplete-classpath -jar simple-socket-fn-logger-${{env.VERSION}}-all.jar

  build-windows-image:
    needs: [build-jar-job]
    name: 'Build Windows Image'
    runs-on: windows-latest

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3.0.0

      - name: Add MSVC to PATH  # See https://www.graalvm.org/reference-manual/native-image/#prerequisites
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: 'Setup GraalVM Environment'
        uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm-version: '22.0.0.2'
          java: java11

      - name: 'Install Native Image Plugin'
        run: |
          gu install native-image

      - name: 'Set up Visual C Build Tools Workload for Visual Studio 2017 Build Tools'
        run: |
          choco install visualstudio2017-workload-vctools

      - name: 'Get JAR Artifact'
        uses: actions/download-artifact@v3.0.0
        with:
          name: 'simple-socket-fn-logger-${{env.VERSION}}-all.jar'

      - name: 'Build Native Image'
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
          native-image --no-server --no-fallback -H:ReflectionConfigurationResources=reflection-config.json -H:IncludeResources=logback.xml -H:Name=simple-socket-fn-logger-${{env.VERSION}}-all --allow-incomplete-classpath -jar simple-socket-fn-logger-${{env.VERSION}}-all.jar